"""Versioned normal program/profile dispatcher; compatibility 0.3 is unchanged."""
import copy
import json
from pathlib import Path

from .collection_query import QueryError, require, validate as validate_query
from .generator import generate as generate_legacy
from .parser import parse
from .validator import validate as validate_legacy

VERSION = "LykoiProgram-1"


def validate_storage(storage, queries):
    try:
        program = validate_legacy(parse(json.dumps(storage["model"])))
        model = program.document
        state = next(s for s in model["state"] if s["id"] == storage["state"])
        types = {t["id"]: t for t in model["types"]}
        record = types[types[state["type"]]["item_type"]]
        fields = {f["name"]: f for f in record["fields"]}
        for q in queries:
            require(q["source"]["collection"] == state["id"], "Collection/state binding mismatch")
            for name, kind in q["source"]["fields"].items():
                f = fields.get(name)
                require(f is not None and not f.get("nullable", False), "Unsupported nullable/missing query field")
                typ = f["type"]
                mapped = "string" if typ in ("prim:string", "prim:timestamp") or types.get(typ, {}).get("kind") == "enum" else None
                require(mapped == kind, "Unsupported model/query field type")
            key = fields[q["source"]["unique_key"]]["id"]
            require(any(i["id"] in state["invariants"] and i.get("kind") == "unique_field" and i.get("field") == key
                        for i in model["invariants"]), "Query identity lacks model uniqueness authority")
            require(q["id"] not in {c["token"] for c in model["commands"]}, "Query/legacy command collision")
        return program
    except (ValueError, TypeError, KeyError, StopIteration) as exc:
        from lykoi_controller import Failure
        raise Failure("UNSUPPORTED_COLLECTION_STORE", reason=str(exc)) from exc


def author(normal):
    if normal.get("profile") == "existing-scalar-1":
        from lykoi_pipeline.scalar_profile import recover
    else:
        from lykoi_pipeline.query_profile import recover
    recover(normal)
    return {"lykoi_version": VERSION, "profile": normal["profile"], "contract": copy.deepcopy(normal)}


def generate(source):
    if source.get("lykoi_version") != VERSION:
        return generate_legacy(validate_legacy(parse(json.dumps(source))))
    require(set(source) == {"lykoi_version", "profile", "contract"}, "Unknown normal program fields")
    if source["profile"] == "existing-scalar-1":
        from lykoi_pipeline import scalar_profile
        contract = scalar_profile.recover(source["contract"])
        p = scalar_profile.structural(contract, scalar_profile.frc.digest(contract))
        b = scalar_profile.bdi(contract, p)
        require(scalar_profile.adequate(contract, b)["outcome"] == "ADEQUATE", "Scalar contract is not adequate")
        return generate_legacy(validate_legacy(parse(json.dumps(scalar_profile.lower(p["facts"], contract["context"]["domains"].get("scalar_base_model"))))))
    from lykoi_pipeline.query_profile import recover, PROFILE
    require(source["profile"] == PROFILE, "Unsupported program profile")
    contract = recover(source["contract"])
    from lykoi_query import contracts
    p = contracts.structural(contract, source["contract"]["document"]["source_frc"])
    b = contracts.bdi(contract, p)
    a = contracts.adequate(contract, b)
    require(a["outcome"] == "IMPLEMENTATION_ADEQUATE", "Query contract is not adequate")
    queries = [validate_query({k: v for k, v in q.items() if k != "origins"}, complete=True) for q in p["queries"]]
    require(len({q["id"] for q in queries}) == len(queries), "Duplicate query commands")
    storage = source["contract"]["storage"]
    prefix = "# Generated by LykoiProgram-1 / collection-query-1; do not edit.\n"
    if storage["kind"] == "model_state":
        legacy = generate_legacy(validate_storage(storage, queries))
        footer = 'if __name__ == "__main__":\n    sys.exit(main())'
        require(legacy.count(footer) == 1, "Legacy backend entrypoint mismatch")
        prefix += legacy.replace(footer, "") + "\nlegacy_main = main\n"
    runtime = Path(__file__).with_name("collection_query_runtime.py").read_text(encoding="utf-8")
    runtime = runtime.replace("def execute(", "def execute_query(").replace("execute(model, records, args)", "execute_query(model, records, args)")
    runtime = runtime.replace("def main(model):", "def standalone_query_main(model):")
    integration = Path(__file__).with_name("profile_runtime.py").read_text(encoding="utf-8")
    return prefix + runtime + "\n" + integration + "\nif __name__ == '__main__':\n    sys.exit(profile_main(" + repr(queries) + ", " + repr({k: v for k, v in storage.items() if k != "model"}) + "))\n"
